server:
   port: 8004

# 通过spring.application.name属性，我们可以指定微服务的名称后续在调用的时候只需要使用该名称就可以进行服务的访问。
spring:
   application:
      name: eureka-hystrix

eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8001/eureka/